# Generated by Django 5.2.8 on 2025-11-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='email_contacto',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='artista',
            name='municipio',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre_artistico',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artista',
            name='ubicacion',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
