# Generated by Django 5.2.8 on 2025-11-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0002_alter_artista_email_contacto_alter_artista_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='pagina_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
